export const activities = {
  title: "Activities",
  description: "Selected research milestones, awards, publications, and academic activities by Zhen Qian.",
  introduction: "Selected research milestones, awards, publications, and academic activities.",
  items: [
    { date: "2024-08-29", dateLabel: "29 Aug 2024", type: "Publication", title: "Nature Geoscience paper accepted", text: "Our paper \"Collaboration between artificial intelligence and Earth science communities for mutual benefit\" was accepted by Nature Geoscience." },
    { date: "2024-08-22", dateLabel: "22 Aug 2024", type: "Award", title: "Provincial Excellent Master's Thesis", text: "My master's thesis received the provincial excellent thesis award (top 1%)." },
    { date: "2024-08-17", dateLabel: "17 Aug 2024", type: "Publication", title: "The Innovation paper accepted", text: "Our paper \"Artificial intelligence for geoscience: Progress, challenges and perspectives\" was accepted by The Innovation." },
    { date: "2024-08-13", dateLabel: "13 Aug 2024", type: "Publication", title: "Remote Sensing paper accepted", text: "Our paper \"Assessment of Rooftop Photovoltaic Potential Considering Building Functions\" was accepted by Remote Sensing." },
    { date: "2024-07-29", dateLabel: "29 Jul 2024", type: "Publication", title: "Urban building-use study accepted", text: "Our work on urban building-use identification with remote sensing and social sensing data was accepted by Geo-spatial Information Science." },
    { date: "2024-05-29", dateLabel: "29 May 2024", type: "Publication", title: "Global Martian crater catalog accepted", text: "Our paper \"A global catalog of Martian impact craters with actual boundaries and degradation states\" was accepted by IJAEOG." },
    { date: "2024-03-29", dateLabel: "29 Mar 2024", type: "Publication", title: "Large-scale building information study accepted", text: "My first-authored paper on extracting building information from high-resolution satellite imagery was accepted by Sustainable Cities and Society." },
    { date: "2024-02-08", dateLabel: "8 Feb 2024", type: "Publication", title: "Photovoltaic noise-barrier study accepted", text: "Our paper \"Power generation assessment of photovoltaic noise barriers across 52 major Chinese cities\" was accepted by Applied Energy." },
    { date: "2023-10-29", dateLabel: "29 Oct 2023", type: "Preprint", title: "Multitask building-detail extraction released", text: "My work \"Multi-task deep learning for large-scale building detail extraction from high-resolution satellite imagery\" was released on arXiv." },
    { date: "2023-10-11", dateLabel: "11 Oct 2023", type: "Publication", title: "Geo-simulation reproducibility paper accepted", text: "Our paper \"Reproducing computational processes in service-based geo-simulation experiments\" was accepted by IJAEOG." },
    { date: "2023-08-11", dateLabel: "11 Aug 2023", type: "Publication", title: "Martian crater delineation paper accepted", text: "Our paper \"Boundary delineator for Martian crater instances with geographic information and deep learning\" was accepted by Remote Sensing." },
    { date: "2023-05-25", dateLabel: "25 May 2023", type: "Publication", title: "Hybrid Earth system modeling review accepted", text: "Our paper \"Iterative integration of deep learning in hybrid Earth surface system modeling\" was accepted by Nature Reviews Earth & Environment." },
    { date: "2023-04-23", dateLabel: "23 Apr 2023", type: "Award", title: "President's Scholarship for Postgraduates", text: "I received the President's Scholarship for Postgraduates." },
    { date: "2023-04-14", dateLabel: "14 Apr 2023", type: "Publication", title: "Rooftop photovoltaic mitigation paper accepted", text: "Our paper \"Carbon mitigation potential afforded by rooftop photovoltaic in China\" was accepted by Nature Communications." },
    { date: "2023-03-22", dateLabel: "22 Mar 2023", type: "Publication", title: "Geo-simulation documentation paper accepted", text: "Our paper \"Documentation strategy for facilitating the reproducibility of geo-simulation experiments\" was accepted by Environmental Modelling & Software." },
    { date: "2022-11-27", dateLabel: "27 Nov 2022", type: "Publication", title: "Deep Solar PV Refiner accepted", text: "Our paper \"Deep Solar PV Refiner\" was accepted by IJAEOG." },
    { date: "2022-08-16", dateLabel: "16 Aug 2022", type: "Publication", title: "Roadside noise-barrier dataset accepted", text: "My first-authored paper \"Vectorized dataset of roadside noise barriers in China using street view imagery\" was accepted by Earth System Science Data." },
    { date: "2022-01-12", dateLabel: "12 Jan 2022", type: "Publication", title: "Rooftop area dataset accepted", text: "Our paper \"Vectorized rooftop area data for 90 cities in China\" was accepted by Scientific Data." },
    { date: "2022-01-09", dateLabel: "9 Jan 2022", type: "Publication", title: "Deep Roof Refiner accepted", text: "My first-authored paper \"Deep Roof Refiner\" was accepted by IJAEOG." },
    { date: "2020-07-28", dateLabel: "28 Jul 2020", type: "Publication", title: "Urban functional-area study accepted", text: "My first-authored paper \"Identification of urban functional areas by coupling satellite images and taxi GPS trajectories\" was accepted by Remote Sensing." },
  ],
};
